name: kroki
description: Class for accessing Kroki.io web service for diagram syntax to svg rendering.
version: 0.0.1
homepage: https://github.com/timmaffett/kroki.dart

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  archive: ^3.3.0
  crypto: ^3.0.2

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.1.0
  build_test: ^2.1.0
  build_web_compilers: ^3.0.0