name: kroki
description: Class for accessing Kroki.io web service for diagram syntax to svg rendering.
version: 0.0.4
homepage: https://github.com/timmaffett/kroki.dart
repository: https://github.com/timmaffett/kroki.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  archive: ^3.3.0
  crypto: ^3.0.1
  http: ^0.13.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0